name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        name: Install pnpm
        with:
          install: true
          cache: true

      - name: Run Astro Check
        run: |
          pnpm run astro check

      - name: Run Typecheck
        run: |
          pnpm run typecheck

      - name: Run Lint
        run: |
          pnpm run lint
