name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  studio:
    name: Studio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Deploy Studio
        id: deploy
        run: |
          DEPLOY_URL=$(pnpm dlx sanity deploy --yes | grep -o 'https://.*.sanity.studio/' | tail -1)
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
          echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_API_DEPLOY_TOKEN }}

      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: sanity
          description: "Sanity Studio deployed to ${{ steps.deploy.outputs.url }}"
          environment-url: ${{ steps.deploy.outputs.url }}
