name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  studio:
    name: Studio
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: pnpm/setup@v3
        name: Install pnpm
        with:
          install: true
          cache: true

      - name: Deploy Studio
        id: deploy
        run: |
          DEPLOY_URL=$(pnpm dlx sanity deploy --yes | grep -o 'https://.*.sanity.studio/' | tail -1)
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
          echo "url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_API_DEPLOY_TOKEN }}

  party:
    name: PartyServer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./workers/party
