name: Generate Types

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  generate-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v5
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update Git Info
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Types
        run: |
          pnpm run typegen

      - name: Commit Changes if any
        id: commit_changes
        run: |
          git add sanity.types.ts sanity.schema.json wrangler.jsonc worker-configuration.d.ts
          if git diff --cached --quiet; then
              echo "No changes to commit."
              echo "changes=false" >> $GITHUB_OUTPUT
          else
              git commit -m "chore: update generated types"
              echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.commit_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.ref_name }}
          title: "chore: update generated types"
          body: "This PR updates the generated types."
          commit-message: "chore: update generated types"
          delete-branch: true
